server:
  port: 9003
  ssl:
    key-store:          "classpath:keystore.p12"
    key-store-password: "12345678"
    key-store-type:     "PKCS12"
    key-alias:          "tomcat"

spring:
  security:
    oauth2:
      client:
        registration:
          misoca:
            provider:      "misoca"
            client-name:   "misoca"
            redirect-uri:  "{baseUrl}/login/oauth2/code/{registrationId}"
            client-id:     "[env]"
            client-secret: "[env]"
            authorization-grant-type:     "authorization_code"
            client-authentication-method: "basic"
            scope:
              - write
        provider: 
          misoca:
            authorization-uri:   "https://app.misoca.jp/oauth2/authorize"
            token-uri:           "https://app.misoca.jp/oauth2/token"
            user-info-uri:       "https://app.misoca.jp/api/v3/user/me"
            user-name-attribute: "id"

logging:
  level:
    com.example: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG 
    org.springframework.security.oauth2: DEBUG

